### ISSUE TITLE
스크롤 모두 내렸을 시 우측하단 백분율 표시가 100% 넘어가는 현상 발생

### ISSUE THREAD

**Issue by ChoSeyoungSLDT** [kkn1125/lessmore-jekyll-theme#10]
기기정보
macOS Big Sur 버전 11.6

브라우저 정보
Google Chrome 버전 98.0.4758.80(공식 빌드) (x86_64)

<img width="147" alt="스크린샷 2022-02-14 오후 1 14 43" src="https://user-images.githubusercontent.com/87627048/153799058-acf06cc9-6e05-4ee0-80a6-ef94feff80c4.png">

**Comment by kkn1125** [comment]
먼저 관심을 가져주셔서 감사합니다 :)
상세한 버그 제보 감사드리며 mac 버전에 대해서도 테스트 해보겠습니다 :)
감사합니다 👍

**Comment by kkn1125** [comment]
안녕하세요 ChoSeyoungSLDT 님, 제보해주신 버그가 수정 됐습니다 :)

현재 다른 활동 때문에 지킬 테마 작업이 지연되고 있습니다. 해당 버그는 불필요한 윈도우 높이 계산과 소수점 계산 차로 인한 오류로 판단하고 계산방식을 수정했습니다.

1. 스크롤 가능 범위 (max범위 도출) = 바디 총 높이 - max(클라이언트 화면 높이 or 모바일 상단바로 인한 갭)
2. 현재 스크롤 위치 / max범위 * 100 = 스크롤 포인트의 백분율 도출

위의 방식은 모두 소수버림으로 값을 받아 개선한 결과입니다.

![image](https://user-images.githubusercontent.com/71887242/153993549-84a48ea2-67f3-4874-8775-5c4f4030a726.png)

특정 환경만 테스트 해본 결과라 아직 미흡하지만 아래 환경에 대해서는 정상작동하는 것으로 보입니다. 모바일에서 브라우저 top bar관련 반응형은 아직 개선 중에 있습니다.

감사합니다~

## 테스트 환경

- Firefox/98.0
- Edg/98.0.1108.50
- Chrome/98.0.4758.82
- Samsung Galaxy S6 - portrait
- IPhone 7 - portrait

**Comment by ChoSeyoungSLDT** [comment]
가끔 찾아와서 보고 있는데 이슈 reopen 하신것 보니 문제가 있나보군요 화이팅입니다.

**Comment by kkn1125** [comment]
가끔 작은 것에 빠져서 다른 것을 못할 때가 많은데 오늘도 배웁니다. 좋은 의견 감사합니다 :)
